# -*- coding: utf-8 -*-
"""KarsangChhombaySherpa240119.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VFxKSkXftIlbayitfvHSIFgwz1zYB8O4
"""

import numpy as np
a=np.empty((2,2))
a

a=np.ones((4,2))
a

a=np.full((2,2),7)
a

a=np.zeros_like([[1,2,3],[4,5,6]])
a

np.zeros((2,2))

a=np.ones_like([[1,2,3],[4,5,6]])
a

new_list=[1,2,3,4,5]
a=np.array(new_list)
a

arr=np.arange(10,49)
arr

import numpy as np
a = np.arange(0,9). reshape(3,3)
a

a=np.eye(3)
a

a=np.random.random((30))
array_mean= a.mean()
array_mean

a=np.random.rand(10,10)
mini=a.min()
maxi=a.max()
mini,maxi

a=np.zeros((10))
a[4]=1
a

arr=[1,2,0,0,4,0]
rev=np.flip(arr)
rev

a=np.array([[1,1,1,1],[1,0,0,1],[1,1,1,1]])
a

a=np.array([[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0],[0,1,0,1,0,1,0,1]])
a